!ObjectType
name: ExtendedTeaserTarget
fields:
  - !Property
    name: target
    sourceName: "target"
    typeName: CMLinkable
  - !Property
    name: callToActionEnabled
    sourceName: "callToActionEnabled?:false"
    typeName: Boolean
  - !Property
    name: callToActionText
    sourceName: "callToActionCustomText?:''"
    typeName: String
