!ObjectType
name: TeaserOverlaySettings
fields:
  - !Property
    name: style
    sourceName: "style?.settings?.style?:{}"
    typeName: Map:String
  - !Property
    name: enabled
    sourceName: "enabled?:false"
    typeName: Boolean
  - !Property
    name: positionX
    sourceName: "positionX?:0"
    typeName: Int
  - !Property
    name: positionY
    sourceName: "positionY?:0"
    typeName: Int
  - !Property
    name: width
    sourceName: "width?:50"
    typeName: Int
