!ObjectType
name: PageGrid
fields:
  - !ContentProperty
    name: cssClassName
    sourceName: "cssClassName"
    typeName: String
  - !ContentProperty
    name: placements
    sourceName: "placements"
    typeName: List:PageGridPlacement
