!ObjectType
name: PageGridPlacement
fields:
  - !ContentProperty
    name: name
    sourceName: "name"
    typeName: String
  - !ContentProperty
    name: viewtype
    sourceName: "viewtype"
    typeName: String
  - !ContentProperty
    name: items
    sourceName: "items"
    typeName: List:CMLinkable
