!ObjectType
name: PageGridPlacement
fields:
  - !Property
    name: name
    typeName: String
  - !Property
    name: viewtype
    typeName: String
  - !Property
    name: items
    typeName: List:CMLinkable
