!ObjectType
name: TimeLine
fields:
  - !Link
    name: defaultTarget
    sourceName: "defaultTarget"
    typeName: CMTeasable
  - !ContentProperty
    name: sequences
    sourceName: "sequences.?[link != null]"
    typeName: List:TimeLineEntry
