!ObjectType
name: TimeLineEntry
fields:
  - !ContentProperty
    name: position
    sourceName: "position"
    typeName: Int
  - !ContentProperty
    name: startTimeMillis
    sourceName: "startTimeMillis"
    typeName: Int
  - !Link
    name: target
    sourceName: "link"
    typeName: CMTeasable
