includedTypes:
  - Content_
  - CMArticle
  - CMCollection
  - CMDownload
  - CMImage
  - CMLinkable
  - CMLocalized
  - CMMedia
  - CMNavigation
  - CMObject
  - CMPicture
  - CMProduct
  - CMResourceBundle
  - CMSite
  - CMTeasable
  - CMTeaser
  - CMVideo
