name: CMLinkable
excludedProperties:
  - htmlDescription
  - htmlTitle
  - keywords
  - linkedSettings
  - localSettings
  - locationTaxonomy
  - resourceBundles2
  - subjectTaxonomy
  - validFrom
  - validTo
customFields:
  - !CustomField
    name: link
    sourceName: "this"
    targetType: String
    dataFetcher: Uri
  - !CustomField
    name: viewtype
    sourceName: "getLink('viewtype')?.layout"
    targetType: String
    dataFetcher: ContentProperty
  - !CustomField
    name: context
    sourceName: "context"
    targetType: CMNavigation
    dataFetcher: Navigation
  - !CustomField
    name: navigationPath
    sourceName: "pathToRoot"
    targetType: List:CMNavigation
    dataFetcher: Navigation
