name: CMLocalized
excludedProperties:
  - locale
  - master
  - masterVersion
customFields:
  - !CustomField
    name: languageId
    sourceName: "locale"
    targetType: String
    dataFetcher: ContentProperty
