name: CMNavigation
excludedProperties:
  - css
  - favicon
  - javaScript
  - placement
  - theme
customFields:
  - !CustomField
    name: children
    sourceName: "$navigation().children"
    targetType: List:CMLinkable
    dataFetcher: ContentProperty
  - !CustomField
    name: grid
    sourceName: "$pageGrid('placement')"
    targetType: PageGrid
    dataFetcher: ContentProperty
  - !CustomField
    name: hidden
    sourceName: "hidden"
    targetType: Boolean
    dataFetcher: ContentProperty
  - !CustomField
    name: hiddenInSitemap
    sourceName: "hiddenInSitemap"
    targetType: Boolean
    dataFetcher: ContentProperty
