name: CMNavigation
excludedProperties:
  - css
  - favicon
  - javaScript
  - placement
  - theme
customFields:
  - !CustomField
    name: children
    targetType: List:CMLinkable
    dataFetcher: Children
  - !CustomField
    name: grid
    sourceName: (placement)
    dataFetcher: PageGrid
  - !CustomField
    name: hidden
    sourceName: (hidden)
    targetType: Boolean
    dataFetcher: ContentProperty
  - !CustomField
    name: hiddenInSitemap
    sourceName: (hiddenInSitemap)
    targetType: Boolean
    dataFetcher: ContentProperty
