name: CMTeaserImpl
customFields:
  - !CustomField
    name: link
    sourceName: "target"
    targetType: String
    dataFetcher: Uri
  - !CustomField
    name: segment
    sourceName: "getLink('target')?.segment"
    targetType: String
    dataFetcher: ContentProperty
  - !CustomField
    name: teaserTarget
    sourceName: "target"
    targetType: CMLinkable
    dataFetcher: Link
  - !CustomField
    name: teaserText
    sourceName: "teaserText"
    fallbackSourceNames:
      - "getLink('target')?.teaserText"
      - "getLink('target')?.detailText"
    targetType: String
    dataFetcher: Richtext
  - !CustomField
    name: teaserTitle
    sourceName: "teaserTitle"
    fallbackSourceNames:
      - "getLink('target')?.teaserTitle"
      - "getLink('target')?.title"
    targetType: String
    dataFetcher: ContentProperty
