name: CMTeaserImpl
customFields:
  - !CustomField
    name: link
    sourceName: (target)
    targetType: String
    dataFetcher: Uri
  - !CustomField
    name: segment
    sourceName: (target)[0].(segment)
    targetType: String
    dataFetcher: Property
  - !CustomField
    name: teaserTarget
    sourceName: (target)
    targetType: CMLinkable
    dataFetcher: Link
