name: CMTeaserImpl
customFields:
  - !CustomField
    name: link
    sourceName: "$extendedLinks('targets', 'target').target"
    targetType: String
    dataFetcher: Uri
  - !CustomField
    name: teaserTarget
    sourceName: "$extendedLinks('targets', 'target').target"
    targetType: CMLinkable
    dataFetcher: Link
  - !CustomField
    name: media
    sourceName: "pictures"
    fallbackSourceNames:
      - "$extendedLinks('targets', 'target', 'CMTeasable').target?.pictures"
    targetType: List:CMMedia
    dataFetcher: Linklist
  - !CustomField
    name: pictures
    sourceName: "pictures"
    fallbackSourceNames:
      - "$extendedLinks('targets', 'target', 'CMTeasable').target?.pictures"
    targetType: List:CMPicture
    dataFetcher: Linklist
  - !CustomField
    name: picture
    sourceName: "pictures"
    fallbackSourceNames:
      - "$extendedLinks('targets', 'target', 'CMTeasable').target?.pictures"
    targetType: CMPicture
    dataFetcher: Link
