name: CMTeasable
excludedProperties:
  - contexts
  - notSearchable
customFields:
  - !CustomField
    name: teaserTarget
    sourceName: "this"
    targetType: CMLinkable
    dataFetcher: Link
  - !CustomField
    name: teaserTargets
    sourceName: "{target: this,
                  callToActionEnabled: !($settings().get('callToActionDisabled', false)),
                  callToActionCustomText: $settings().get('callToActionCustomText', '')}"
    targetType: List:ExtendedTeaserTarget
    dataFetcher: ExtendedLinklist
  - !CustomField
    name: teaserOverlaySettings
    sourceName: "localSettings?.teaserOverlay?:{enabled: false}"
    targetType: TeaserOverlaySettings
    dataFetcher: Struct
  - !CustomField
    name: media
    sourceName: "pictures"
    targetType: List:CMMedia
    dataFetcher: Linklist
  - !CustomField
    name: pictures
    sourceName: "pictures"
    targetType: List:CMPicture
    dataFetcher: Linklist
  - !CustomField
    name: picture
    sourceName: "pictures"
    targetType: CMPicture
    dataFetcher: Link
  - !CustomField
    name: teaserText
    sourceName: "teaserText"
    fallbackSourceNames:
      - "detailText"
    targetType: String
    dataFetcher: Richtext
  - !CustomField
    name: teaserTitle
    sourceName: "teaserTitle"
    fallbackSourceNames:
      - "title"
    targetType: String
    dataFetcher: ContentProperty
