name: CMTeasable
excludedProperties:
  - contexts
  - notSearchable
customFields:
  - !CustomField
    name: teaserTarget
    sourceName: this
    targetType: CMLinkable
    dataFetcher: Link
  - !CustomField
    name: media
    sourceName: (pictures)
    targetType: CMMedia
    dataFetcher: Linklist
  - !CustomField
    name: pictures
    sourceName: (pictures)
    targetType: CMPicture
    dataFetcher: Linklist
  - !CustomField
    name: picture
    sourceName: (pictures)
    targetType: CMPicture
    dataFetcher: Link
