name: CMVideo
excludedProperties:
  - asset
  - data
  - dataUrl
customFields:
  - !CustomField
    name: timeLine
    sourceName: "getLink('viewtype')?.layout == 'shoppable'? timeLine : null"
    targetType: TimeLine
    dataFetcher: Struct
