name: CMVideo
excludedProperties:
  - asset
  - data
  - dataUrl
customFields:
  - !CustomField
    name: timeLine
    sourceName: (timeLine)
    targetType: TimeLine
    dataFetcher: Struct
    directives:
      - !Directive
        name: if
        arguments:
          test: getLink('viewtype')?.getString('layout') == 'shoppable'
