name: Content_
customFields:
  - !CustomField
    name: __baseinterface
    targetType: String
    nonNull: true
    dataFetcher: Meta
  - !CustomField
    name: __interfaces
    targetType: List:String
    nonNull: true
    dataFetcher: Meta
  - !CustomField
    name: this
    targetType: Content_
    nonNull: true
    dataFetcher: Property
  - !CustomField
    name: _id
    sourceName: id
    targetType: String
    nonNull: true
    dataFetcher: Property
  - !CustomField
    name: _type
    sourceName: type
    targetType: String
    nonNull: true
    dataFetcher: Property
  - !CustomField
    name: _name
    sourceName: name
    targetType: String
    nonNull: true
    dataFetcher: Property
