name: Content_
customFields:
  - !CustomField
    name: __baseinterface
    targetType: String
    nonNull: true
    dataFetcher: Meta
  - !CustomField
    name: __interfaces
    targetType: List:String
    nonNull: true
    dataFetcher: Meta
  - !CustomField
    name: _id
    sourceName: "_id"
    targetType: String
    nonNull: true
    dataFetcher: Property
  - !CustomField
    name: _type
    sourceName: "_type"
    targetType: String
    nonNull: true
    dataFetcher: Property
  - !CustomField
    name: _name
    sourceName: "_name"
    targetType: String
    nonNull: true
    dataFetcher: Property
  - !CustomField
    name: _creationDate
    sourceName: "_creationDate"
    targetType: String
    nonNull: true
    dataFetcher: Property
  - !CustomField
    name: _modificationDate
    sourceName: "_modificationDate"
    targetType: String
    nonNull: true
    dataFetcher: Property
